server:
  port: 10002

eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:10001/eureka/,http://peer3:10003/eureka/